FROM ubuntu:latest

LABEL maintainer "alves.rjc+docker@gmail.com"

RUN apt update && \
    apt install -y \
    ca-certificates \
    coreutils \
    netbase \
    python \
    unzip \
    wget \
    && \
    apt clean && \
    rm -rf /var/lib/apt/lists

RUN mkdir -p /data && \
    mkdir -p /opt/ngless/bin && \
    mkdir -p /opt/ngless/share/ngless && \
    wget -O /opt/ngless/bin/ngless https://github.com/ngless-toolkit/ngless/releases/download/v1.0.1/NGLess-1.0.1-static-Linux64 && \
    chmod +x /opt/ngless/bin/ngless

ENTRYPOINT ["/opt/ngless/bin/ngless"]
WORKDIR "/data"
