BootStrap: docker
From: nglesstoolkit/ng-meta-marine:1.0.1

%environment
    export PATH=/opt/ngless/bin:$PATH
    export XDG_RUNTIME_DIR=""

%apprun ng-meta-marine-profiler
    ngless /opt/ngless/bin/marine-profiler.ngl "$@"

%runscript
    ngless /opt/ngless/bin/marine-profiler.ngl "$@"
