FROM nglesstoolkit/ng-meta-marine:1.0.0

LABEL maintainer "alves.rjc+docker@gmail.com"

RUN wget -O /opt/ngless/bin/ngless https://github.com/ngless-toolkit/ngless/releases/download/v1.0.1/NGLess-1.0.1-static-Linux64 && \
    chmod +x /opt/ngless/bin/ngless

ENTRYPOINT ["/opt/ngless/bin/ngless", "/opt/ngless/bin/marine-profiler.ngl"]
CMD []
